#!/bin/sh

SELF=$(readlink -f "$0")
HERE=${SELF%/*}
export CLASSPATH="${HERE}/CSCSigner.jar:${HERE}/libs/bcpkix-jdk15on-1.59.jar:${HERE}/libs/bcprov-jdk15on-1.59.jar:${HERE}/libs/commons-lang3-3.7.jar:${HERE}/libs/commons-logging-1.2.jar:${HERE}/libs/fontbox-2.0.13.jar:${HERE}/libs/gson-2.8.2.jar:${HERE}/libs/jjwt-api-0.10.6.jar:${HERE}/libs/jjwt-impl-0.10.6.jar:${HERE}/libs/log4j-1.2.17.jar:${HERE}/libs/pdfbox-2.0.13.jar:${HERE}/libs/slf4j-api-1.7.25.jar:${HERE}/libs/slf4j-log4j12-1.7.25.jar"
export JARFILE="${HERE}/CSCSigner.jar"
export JAVA_HOME="${HERE}/jre1.8.0_141"
export PATH="${JAVA_HOME}/bin/:${HERE}/${PATH:+:$PATH}"
EXEC=$(grep -e '^Exec=.*' "${HERE}"/*.desktop | head -n 1 | cut -d "=" -f 2 | cut -d " " -f 1)
exec "${EXEC}" "$@"
